### PR TITLE
refactor(test): e2e test configuration and launch script

### PR DESCRIPTION
**Pull request by divdavem**

### CODE REVIEW

**Comment by quentinderoubaix** [comment]
The command `npm run e2e chromium react rating -- --coverage` is failing as the demo workspace is missing the command `dev:coverage`

**Comment by quentinderoubaix** [comment]
> The command `npm run e2e chromium react rating -- --coverage` is failing as the demo workspace is missing the command `dev:coverage`

It probably should not need the demo to be running either right ?

**Comment by divdavem** [comment]
> > The command `npm run e2e chromium react rating -- --coverage` is failing as the demo workspace is missing the command `dev:coverage`
> 
> It probably should not need the demo to be running either right ?

Actually, the meaning of the command changed a bit compared to what was done previously. The rating test is looked for in all projects, including the demo project, that's why the demo is started.

**Review by quentinderoubaix — APPROVED** [review]
LGTM !

**Comment by quentinderoubaix** [comment]
Maybe we should add a few lines in DEVELOPER.md to explain the difference of main vs singleBrowser vs demo.

**Comment by divdavem** [comment]
@quentinderoubaix Thank you for your review!

**Pull request merged**
