### PR TITLE
feat: making auUse synchronous

### PR DESCRIPTION
**Pull request by divdavem**
Now that https://github.com/angular/angular/issues/50320 is fixed, it should be possible to change any angular signal at any time and there should be no need anymore to delay the call of directives.

### CODE REVIEW

**Comment by divdavem** [comment]
Note that this seems to break opening transitions in the accordion.

**Review by quentinderoubaix — APPROVED** [review]
LGTM !
thx for the pr @divdavem

**Comment by divdavem** [comment]
@quentinderoubaix Thank you for your review!

**Comment by quentinderoubaix** [comment]
closes #114

**Pull request merged**
